language: vim

os:
    - linux
    - osx

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/joereynolds/SQHell.vim

  git clone https://github.com/vim/vim
  cd vim
  ./configure --with-features=huge
  make
  sudo make install
  cd -


script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=SQHell.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/*' > /dev/null
